name: flexidot
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8,<3.13
  - biopython
  - colormap
  - colour
  - easydev
  - matplotlib
  - numpy
  - regex
  - pip
  - pip:
      - pytest
      - pytest-cov
      - hatch


